# github action for running python script

\
name: ISDI_Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          # Validate only new pull requests
          VALIDATE_ALL_CODEBASE: false
          # Uncommenting the following enables linting for only Python and bash files
          # VALIDATE_PYTHON: true
          # VALIDATE_BASH: true
          # VALIDATE_BASH_EXEC: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
